version: "3"
services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile-Dev
    command: ["npm", "run", "client:dev"]
    depends_on:
      - server
    environment:
      - BASE_URL=http://server:3000
    image: slay
    networks:
      - slay
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/slay
      - /usr/src/slay/node_modules
      - /usr/src/slay/website/client/node_modules
  server:
    build:
      context: .
      dockerfile: ./Dockerfile-Dev
    command: ["npm", "start"]
    depends_on:
      - mongo
    environment:
      - NODE_DB_URI=mongodb://mongo/donPabloNow
    image: slay
    networks:
      - slay
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/slay
      - /usr/src/slay/node_modules
  mongo:
    image: mongo:3.6
    networks:
      - slay
    ports:
      - "27017:27017"
networks:
  slay:
    driver: bridge
