apiVersion: v1
kind: Pod
metadata:
  name: slay
  labels:
    name: slay
spec:
  containers:
#    - image: mongo:latest
#      name: mongo
#      ports:
#        - containerPort: 27017
#          name: mongo
    - image: ksonney/donPabloNow:latest
      name: slay
      env:
        - name: NODE_DB_URI
          value: mongodb://mongosvc/donPabloNow
      ports:
        - containerPort: 3000
          hostPort: 3000
          name: slay
