apiVersion: v1
kind: ReplicationController
metadata:
  name: slay
  labels:
    name: slay
spec:
  replicas: 4
  selector:
    name: slay
  template:
    metadata:
      labels:
        name: slay
    spec:
      containers:
      - name: slay
        image: ksonney/donPabloNow:latest
        env:
          - name: NODE_DB_URI
            value: mongodb://mongosvc/donPabloNow
        ports:
          - containerPort: 3000
            hostPort: 3000
            name: slay
